/* Generated By:JavaCC: Do not edit this line. CalenderParserConstants.java */
package edu.curtin.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalenderParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EVENT = 6;
  /** RegularExpression Id. */
  int DATE = 7;
  /** RegularExpression Id. */
  int TIME = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int STRING_LITERAL = 10;
  /** RegularExpression Id. */
  int ALL_DAY = 11;
  /** RegularExpression Id. */
  int PLUGIN = 12;
  /** RegularExpression Id. */
  int KEY = 13;
  /** RegularExpression Id. */
  int CLASSNAME = 14;
  /** RegularExpression Id. */
  int VALUE = 15;
  /** RegularExpression Id. */
  int IDENTIFIER = 16;
  /** RegularExpression Id. */
  int CURLY_OPEN = 17;
  /** RegularExpression Id. */
  int CURLY_CLOSE = 18;
  /** RegularExpression Id. */
  int COLON = 19;
  /** RegularExpression Id. */
  int COMMA = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"event\"",
    "<DATE>",
    "<TIME>",
    "<NUMBER>",
    "<STRING_LITERAL>",
    "\"all-day\"",
    "\"plugin\"",
    "<KEY>",
    "<CLASSNAME>",
    "<VALUE>",
    "<IDENTIFIER>",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\",\"",
  };

}
